#!/bin/bash

#SBATCH -o /home/hpc/<project>/<user>/myjob.%j.out
#SBATCH -D /home/hpc/<project>/<user>
#SBATCH -J myjob
#SBATCH --get-user-env
#SBATCH --partition=snb
#SBATCH --ntasks=36
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=end
#SBATCH --mail-user=kunuthur@in.tum.de
#SBATCH --export=NONE
#SBATCH --time=01:30:00

source /etc/profile.d/modules.sh

mpiexec.hydra -genv OMP_NUM_THREADS 16 -ppn 1 -n 8 ./a.out


