#!/bin/bash

#SBATCH -o /home/hpc/t1221/t1221al/turbulent_HPC/NS-EOF/myjob.%j.out
#SBATCH -D /home/hpc/t1221/t1221al/turbulent_HPC/NS-EOF
#SBATCH -J myjob
#SBATCH --get-user-env
#SBATCH --partition=snb
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=end
#SBATCH --mail-user=kunuthur@in.tum.de
#SBATCH --export=NONE
#SBATCH --time=01:30:00

source /etc/profile.d/modules.sh

mpiexec.hydra -genv OMP_NUM_THREADS 1 -ppn 32 -n 1 /home/hpc/t1221/t1221al/turbulent_HPC/NS-EOF/ns /home/hpc/t1221/t1221al/turbulent_HPC/NS-EOF/



